# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    groups:
      vite:
        patterns:
          - "vite"
          - "@vitejs/"
      test:
        patterns:
          - "vitest"
          - "@vitest/*"
          - "jsdom"
      prettier:
        patterns:
          - "prettier"
          - "eslint-plugin-prettier"
          - "eslint-config-prettier"
          - "prettier-plugin-organize-imports"
      mui:
        patterns:
          - "@emotion*"
          - "@mui*/"
      react:
        patterns:
          - "react*"
          - "@types/react"
      types:
        patterns:
          - "@types*"
          - "types*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
