name: Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          # @see https://github.com/marketplace/actions/setup-pnpm#use-cache-to-reduce-installation-time
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - run: pnpm ci
      - run: pnpm run lint
      - run: pnpm run build
      - run: pnpm test
      - name: "Upload Coverage"
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
          retention-days: 3
